name: Tag on PR Merge

on:
  pull_request:
    types: [opened, synchronize]
  # push:
  #   branches:
  #     - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version you are using

      - name: Get version from package.json
        uses: bbonkr/get-version-action@v1
        id: package_version
        with:
          project: './package.json'

      - name: Create and push tag
        run: |
          echo "v${{ steps.package_version.outputs.version }}"  
        # run: |
        #   git tag -a "v${{ steps.package_version.outputs.version }}" -m "Version v${{ steps.package_version.outputs.version }}"
        #   git push origin "v${{ steps.package_version.outputs.version }}"