name: Tag on PR Merge

on:
  pull_request:
    types: [opened, synchronize]
  # push:
  #   branches:
  #     - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get version from package.json
        uses: bbonkr/get-version-action@v1
        id: package_version
        with:
          project: './package.json'
      
      - name: Check if tag exists
        run: |
          git fetch --tags
          if git rev-parse "v${{ steps.package_version.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag v${{ steps.package_version.outputs.version }} already exists"
            exit 1
          fi

      - name: Create and push tag
        run: |
          git config --global user.email "dev@meshed3d.com"
          git config --global user.name "Landing Dev"
          git tag -a "v${{ steps.package_version.outputs.version }}" -m "Version v${{ steps.package_version.outputs.version }}"
          git push origin "v${{ steps.package_version.outputs.version }}"