name: Tag on PR Merge

on:
  pull_request:
    types: [opened, synchronize]
  # push:
  #   branches:
  #     - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get version from package.json
        uses: bbonkr/get-version-action@v1
        id: package_version
        with:
          project: './package.json'

      - name: Check tag duplication
        uses: bbonkr/git-tag-check-action@v1
        id: tag_check
        with:
          tag: "v${{ steps.package_version.outputs.version }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Print tag if not found
        if: steps.tag_check.outputs.tag == ''
        run: |
          echo "Tag: v${{ steps.package_version.outputs.version }}"