name: On Release

on:
  release:
    types: [published]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Print Release Tag
        run: echo ${{ github.event.release.tag_name }}